/**
 * Build Database Script
 *
 * Merges scraped contractor data from all 10 states into a single
 * TypeScript file for the SubPaid app.
 *
 * Usage: npx tsx scripts/build-database.ts
 *
 * Input:  scripts/output/{state}-contractors.json
 * Output: src/lib/contractors-data.ts (TypeScript export)
 */

import * as fs from 'fs';
import * as path from 'path';

interface Contractor {
  id: string;
  licenseNumber: string;
  licenseType: string;
  licenseStatus: 'active' | 'inactive' | 'suspended' | 'expired';
  classifications: string[];
  businessName: string;
  ownerName?: string;
  phone?: string;
  email?: string;
  website?: string;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  county?: string;
  issueDate: string;
  expirationDate: string;
  lastUpdated: string;
  payScore?: number;
  reviewCount?: number;
  avgPaymentDays?: number;
  claimed: boolean;
  claimedByUserId?: string;
  dataSource: string;
  sourceUrl?: string;
  verified: boolean;
  verifiedAt?: string;
  createdAt: string;
  updatedAt: string;
}

// All 10 states and their output JSON filenames
const STATE_FILES: Record<string, { file: string; emoji: string; name: string }> = {
  FL: { file: 'florida-contractors.json', emoji: '🌴', name: 'Florida' },
  CA: { file: 'california-contractors.json', emoji: '☀️', name: 'California' },
  AZ: { file: 'arizona-contractors.json', emoji: '🌵', name: 'Arizona' },
  NC: { file: 'northcarolina-contractors.json', emoji: '🌲', name: 'North Carolina' },
  TX: { file: 'texas-contractors.json', emoji: '⭐', name: 'Texas' },
  GA: { file: 'georgia-contractors.json', emoji: '🍑', name: 'Georgia' },
  OH: { file: 'ohio-contractors.json', emoji: '🔴', name: 'Ohio' },
  PA: { file: 'pennsylvania-contractors.json', emoji: '🔔', name: 'Pennsylvania' },
  IL: { file: 'illinois-contractors.json', emoji: '🏙️', name: 'Illinois' },
  NY: { file: 'newyork-contractors.json', emoji: '🗽', name: 'New York' },
};

function main() {
  console.log('🏗️  SubPaid Contractor Database Builder');
  console.log('=======================================');
  console.log('');

  const outputDir = path.join(__dirname, 'output');
  const allContractors: Contractor[] = [];
  const stateCounts: Record<string, number> = {};

  // Load data from all states
  for (const [stateCode, config] of Object.entries(STATE_FILES)) {
    const filePath = path.join(outputDir, config.file);
    if (fs.existsSync(filePath)) {
      const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
      console.log(`${config.emoji} Loaded ${data.length} ${config.name} contractors`);
      allContractors.push(...data);
      stateCounts[stateCode] = data.length;
    } else {
      console.log(`⚠️  No ${config.name} data found (${config.file})`);
    }
  }

  if (allContractors.length === 0) {
    console.log('');
    console.log('❌ No contractor data to process.');
    console.log('   Run the scrapers first, or the app will use pre-populated data from contractors-data.ts');
    return;
  }

  // Deduplicate (by license number + state)
  const seen = new Set<string>();
  const deduped = allContractors.filter((c) => {
    const key = `${c.state}-${c.licenseNumber}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  console.log('');
  console.log(`📊 Total: ${deduped.length} unique contractors (${allContractors.length - deduped.length} duplicates removed)`);

  // Re-index IDs using per-state counters
  const stateIndexes: Record<string, number> = {};
  const reindexed = deduped.map((c) => {
    const prefix = c.state.toLowerCase();
    stateIndexes[c.state] = (stateIndexes[c.state] || 0) + 1;
    return { ...c, id: `${prefix}-${String(stateIndexes[c.state]).padStart(3, '0')}` };
  });

  // Generate header comment with per-state stats
  const stateStatsLines = Object.entries(stateCounts)
    .map(([code, count]) => `// ${STATE_FILES[code].name}: ${count} contractors`)
    .join('\n');

  // Generate TypeScript output
  const tsContent = `// Auto-generated by scripts/build-database.ts
// Last built: ${new Date().toISOString()}
// Total contractors: ${reindexed.length}
//
${stateStatsLines}

import { Contractor } from './db';

export const contractorsData: Contractor[] = ${JSON.stringify(reindexed, null, 2)};
`;

  const outputPath = path.join(__dirname, '..', 'src', 'lib', 'contractors-data.ts');
  fs.writeFileSync(outputPath, tsContent);
  console.log(`💾 Written to ${outputPath}`);

  // Stats
  console.log('');
  console.log('📈 Database Stats:');
  for (const [code, count] of Object.entries(stateCounts)) {
    const padding = STATE_FILES[code].name.padEnd(18);
    console.log(`   ${padding}${count} contractors`);
  }
  console.log(`   ${'Total'.padEnd(18)}${reindexed.length} contractors`);
  console.log('');

  const statusCounts = {
    active: reindexed.filter((c) => c.licenseStatus === 'active').length,
    inactive: reindexed.filter((c) => c.licenseStatus === 'inactive').length,
    expired: reindexed.filter((c) => c.licenseStatus === 'expired').length,
    suspended: reindexed.filter((c) => c.licenseStatus === 'suspended').length,
  };
  console.log('   Status breakdown:');
  console.log(`     Active:    ${statusCounts.active}`);
  console.log(`     Inactive:  ${statusCounts.inactive}`);
  console.log(`     Expired:   ${statusCounts.expired}`);
  console.log(`     Suspended: ${statusCounts.suspended}`);
  console.log('');
  console.log('✅ Database build complete!');
}

main();
