/**
 * Build Database Script
 *
 * Merges scraped contractor data from Florida DBPR and California CSLB
 * into a single TypeScript file for the SubPaid app.
 *
 * Usage: npx tsx scripts/build-database.ts
 *
 * Input:
 *   - scripts/output/florida-contractors.json
 *   - scripts/output/california-contractors.json
 *
 * Output:
 *   - src/lib/contractors-data.ts (TypeScript export)
 */

import * as fs from 'fs';
import * as path from 'path';

interface Contractor {
  id: string;
  licenseNumber: string;
  licenseType: string;
  licenseStatus: 'active' | 'inactive' | 'suspended' | 'expired';
  classifications: string[];
  businessName: string;
  ownerName?: string;
  phone?: string;
  email?: string;
  website?: string;
  address: string;
  city: string;
  state: 'FL' | 'CA';
  zipCode: string;
  county?: string;
  issueDate: string;
  expirationDate: string;
  lastUpdated: string;
  payScore?: number;
  reviewCount?: number;
  avgPaymentDays?: number;
  claimed: boolean;
  claimedByUserId?: string;
  dataSource: 'FL_DBPR' | 'CA_CSLB';
  sourceUrl?: string;
  verified: boolean;
  verifiedAt?: string;
  createdAt: string;
  updatedAt: string;
}

function main() {
  console.log('🏗️  SubPaid Contractor Database Builder');
  console.log('=======================================');
  console.log('');

  const outputDir = path.join(__dirname, 'output');
  const allContractors: Contractor[] = [];

  // Load Florida data
  const flPath = path.join(outputDir, 'florida-contractors.json');
  if (fs.existsSync(flPath)) {
    const flData = JSON.parse(fs.readFileSync(flPath, 'utf-8'));
    console.log(`🌴 Loaded ${flData.length} Florida contractors`);
    allContractors.push(...flData);
  } else {
    console.log('⚠️  No Florida data found at scripts/output/florida-contractors.json');
    console.log('   Run: npx tsx scripts/scrapers/florida-dbpr.ts');
  }

  // Load California data
  const caPath = path.join(outputDir, 'california-contractors.json');
  if (fs.existsSync(caPath)) {
    const caData = JSON.parse(fs.readFileSync(caPath, 'utf-8'));
    console.log(`☀️  Loaded ${caData.length} California contractors`);
    allContractors.push(...caData);
  } else {
    console.log('⚠️  No California data found at scripts/output/california-contractors.json');
    console.log('   Run: npx tsx scripts/scrapers/california-cslb.ts');
  }

  if (allContractors.length === 0) {
    console.log('');
    console.log('❌ No contractor data to process.');
    console.log('   Run the scrapers first, or the app will use pre-populated data from contractors-data.ts');
    return;
  }

  // Deduplicate (by license number + state)
  const seen = new Set<string>();
  const deduped = allContractors.filter((c) => {
    const key = `${c.state}-${c.licenseNumber}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  console.log('');
  console.log(`📊 Total: ${deduped.length} unique contractors (${allContractors.length - deduped.length} duplicates removed)`);

  // Re-index IDs
  let flIndex = 0;
  let caIndex = 0;
  const reindexed = deduped.map((c) => {
    if (c.state === 'FL') {
      flIndex++;
      return { ...c, id: `fl-${String(flIndex).padStart(3, '0')}` };
    } else {
      caIndex++;
      return { ...c, id: `ca-${String(caIndex).padStart(3, '0')}` };
    }
  });

  // Generate TypeScript output
  const tsContent = `// Auto-generated by scripts/build-database.ts
// Last built: ${new Date().toISOString()}
// Total contractors: ${reindexed.length}
//
// Florida DBPR: ${flIndex} contractors
// California CSLB: ${caIndex} contractors

import { Contractor } from './db';

export const contractorsData: Contractor[] = ${JSON.stringify(reindexed, null, 2)};
`;

  const outputPath = path.join(__dirname, '..', 'src', 'lib', 'contractors-data.ts');
  fs.writeFileSync(outputPath, tsContent);
  console.log(`💾 Written to ${outputPath}`);

  // Stats
  console.log('');
  console.log('📈 Database Stats:');
  console.log(`   Florida:    ${flIndex} contractors`);
  console.log(`   California: ${caIndex} contractors`);
  console.log(`   Total:      ${reindexed.length} contractors`);
  console.log('');

  const statusCounts = {
    active: reindexed.filter((c) => c.licenseStatus === 'active').length,
    inactive: reindexed.filter((c) => c.licenseStatus === 'inactive').length,
    expired: reindexed.filter((c) => c.licenseStatus === 'expired').length,
    suspended: reindexed.filter((c) => c.licenseStatus === 'suspended').length,
  };
  console.log('   Status breakdown:');
  console.log(`     Active:    ${statusCounts.active}`);
  console.log(`     Inactive:  ${statusCounts.inactive}`);
  console.log(`     Expired:   ${statusCounts.expired}`);
  console.log(`     Suspended: ${statusCounts.suspended}`);
  console.log('');
  console.log('✅ Database build complete!');
}

main();
